In [1]:
import torch
import torch.nn.functional as F

d:\anaconda\envs\DeepLearning\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [ ]:
# a = torch.arange(0,4).view(2,2)
# a = torch.Tensor([[0,1],[2,0]], dtype=torch.int64)  错误，torch1.8版本以后，Tensor不支持指定类型
a = torch.tensor([[0, 1], [2, 0]], dtype=torch.int64)
print(a)

tensor([[0, 1],
        [2, 0]])


In [40]:
a = F.one_hot(a, 4)
print(a)

tensor([[[1, 0, 0, 0],
         [0, 1, 0, 0]],

        [[0, 0, 1, 0],
         [1, 0, 0, 0]]])


In [41]:
b = a.permute(2,0,1)
print(b)

tensor([[[1, 0],
         [0, 1]],

        [[0, 1],
         [0, 0]],

        [[0, 0],
         [1, 0]],

        [[0, 0],
         [0, 0]]])


In [23]:
c = b[0]
print(c)

tensor([[1, 0],
        [0, 0]])


In [42]:
idx, topx = torch.where(b[0])
print(idx)
print(topx)

tensor([0, 1])
tensor([0, 1])
