## 基本概念

Tensor（张量）是深度学习中常使用的一种数据结构，能够**包含计算图，能够自动求导、GPU加速**

Numpy是python中一个科学计算基本库，提供了一个多维数组对象 `ndarray`.主要用于数值计算，不支持自动求导，仅支持CPU计算

Tensor 和 Numpy 可以相互转换，但需要注意设备位置（需要在CPU上），转换方法：

1. .numpy():将 tensor 转换为 numpy， torch.from_numpy(): 将 numpy 转换为 tensor。注意这种转换方式是指两者共享相同的内存，一个改变另一个也会改变
2. torch.tensor(): 将 tensor 转换为 numpy，返回的Tensor和原来的numpy数据不再共享内存。所以计算速度慢

## 创建tensor

torch.Tensor()是指创建一个浮点数的 tensor， 等同于 torch.FloatTensor()，类似的还有 torch.IntTensor, torch.LongTensor(), torch.DoubleTensor().

torch.tensor()需要在里面指定 tensor 类型。

In [1]:
import torch
import torch.nn.functional as F

d:\anaconda\envs\DeepLearning\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [ ]:
a = torch.Tnesor([0, 1])
b = torch.FloatTensor([0, 1])

c = torch.tensor([0., 1.])

print(a.type(), b.type(), c.type())

In [ ]:
# a = torch.arange(0,4).view(2,2)
# a = torch.Tensor([[0,1],[2,0]], dtype=torch.int64)  错误，torch1.8版本以后，Tensor不支持指定类型
a = torch.tensor([[0, 1], [2, 0]], dtype=torch.int64)
print(a)

tensor([[0, 1],
        [2, 0]])


In [40]:
a = F.one_hot(a, 4)
print(a)

tensor([[[1, 0, 0, 0],
         [0, 1, 0, 0]],

        [[0, 0, 1, 0],
         [1, 0, 0, 0]]])


In [41]:
b = a.permute(2,0,1)
print(b)

tensor([[[1, 0],
         [0, 1]],

        [[0, 1],
         [0, 0]],

        [[0, 0],
         [1, 0]],

        [[0, 0],
         [0, 0]]])


In [23]:
c = b[0]
print(c)

tensor([[1, 0],
        [0, 0]])


In [42]:
idx, topx = torch.where(b[0])
print(idx)
print(topx)

tensor([0, 1])
tensor([0, 1])


In [5]:
a = torch.arange(0,4).view(2,2)
print(a)
b = a[0,0]
print(b)
c = a[[0,1],0]
print(c)
d = a[[0,1],[0,1]]
print(d)

tensor([[0, 1],
        [2, 3]])
tensor(0)
tensor([0, 2])
tensor([0, 3])
